debete_project_ruby/config/routes.rb
Rails.application.routes.draw do
  resources :perceptrons

  root 'perceptrons#risk_of_diabete'

  get 'perceptrons' => 'perceptrons#risk_of_diabete'

end

debete_project_ruby/app/models/perceptron.rb
class Perceptron < ActiveRecord::Base
end

debete_project_ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

debete_project_ruby/app/controllers/perceptrons_controller.rb
class PerceptronsController < ApplicationController
  before_action :set_perceptron, only: [:show, :edit, :update, :destroy]

  
## Implementing ANN using Perceptron model for calculating risks of having Diabete-------------------##
  def risk_of_diabete

    sum = 0.0
    @output = 0

    ## Decide later what should be inputs
    input = [params[:age], params[:height], params[:weight]]

    ## According to the example : expert_weight should be between -1 and 1
    expert_weight = [0.1, 0.2, 0.3]


    for i in 0..(input.length-1)
      sum += input.at(i).to_f*expert_weight.at(i).to_f
    end

    @output = activate(sum)

  end

  ## The activation function the sign of the sum
  def activate(sum)
    if sum > 0
      activated_output = 1
    else
      activated_output = -1
    end

    return activated_output
  end




##--------------------------------------------------------------------------------------------------##


## Below: From scaffolding, do not care

  # GET /perceptrons
  # GET /perceptrons.json
  def index
    @perceptrons = Perceptron.all
  end

  # GET /perceptrons/1
  # GET /perceptrons/1.json
  def show
  end

  # GET /perceptrons/new
  def new
    @perceptron = Perceptron.new
  end

  # GET /perceptrons/1/edit
  def edit
  end

  # POST /perceptrons
  # POST /perceptrons.json
  def create
    @perceptron = Perceptron.new(perceptron_params)

    respond_to do |format|
      if @perceptron.save
        format.html { redirect_to @perceptron, notice: 'Perceptron was successfully created.' }
        format.json { render :show, status: :created, location: @perceptron }
      else
        format.html { render :new }
        format.json { render json: @perceptron.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perceptrons/1
  # PATCH/PUT /perceptrons/1.json
  def update
    respond_to do |format|
      if @perceptron.update(perceptron_params)
        format.html { redirect_to @perceptron, notice: 'Perceptron was successfully updated.' }
        format.json { render :show, status: :ok, location: @perceptron }
      else
        format.html { render :edit }
        format.json { render json: @perceptron.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perceptrons/1
  # DELETE /perceptrons/1.json
  def destroy
    @perceptron.destroy
    respond_to do |format|
      format.html { redirect_to perceptrons_url, notice: 'Perceptron was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perceptron
      @perceptron = Perceptron.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perceptron_params
      params[:perceptron]
    end
end

debete_project_ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

debete_project_ruby/app/helpers/perceptrons_helper.rb
module PerceptronsHelper
end

debete_project_ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DebeteProjectRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse">
      </button>
      <%= link_to "Risk of Diabete", '#', :class => "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Home", '#' %></li>
        <li><%= link_to "....", '#' %></li>
      </ul>
    </div>
  </div>
</nav>

  <%= yield %>

<section id="footer">
  <div class="container">
    <p class="text-center">&copy; Copyright 2015 DST Project. All Rights Reserved.</p>
  </div>
</section>

</body>
</html>

debete_project_ruby/app/views/perceptrons/_form.html.erb
<%= form_for(@perceptron) do |f| %>
  <% if @perceptron.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perceptron.errors.count, "error") %> prohibited this perceptron from being saved:</h2>

      <ul>
      <% @perceptron.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

debete_project_ruby/app/views/perceptrons/edit.html.erb
<h1>Editing Perceptron</h1>

<%= render 'form' %>

<%= link_to 'Show', @perceptron %> |
<%= link_to 'Back', perceptrons_path %>

debete_project_ruby/app/views/perceptrons/index.html.erb
<p id="notice"><%= notice %></p>

debete_project_ruby/app/views/perceptrons/new.html.erb
<h1>New Perceptron</h1>

<%= render 'form' %>

<%= link_to 'Back', perceptrons_path %>

debete_project_ruby/app/views/perceptrons/risk_of_diabete.html.erb
<div class="container">
  <div class="page-header">
    <h1>Enter data</h1>
  </div>
  <br/>

  <div class="row>"
    <%=  form_tag({controller: "perceptrons", action: "risk_of_diabete"}, method: "get") do %>
      <div class="col-md-2">
        <%= label_tag(:age, "Age: ") %>
      </div>
      <div class="col-md-10">
        <%= text_field_tag(:age) %>
      </div>
      <br/>

      <div class="col-md-2">
        <%= label_tag(:height, "Height: ") %>
      </div>
      <div class="col-md-10">
        <%= text_field_tag(:height) %>
      </div>
      <br/>

      <div class="col-md-2">
        <%= label_tag(:weight, "Weight: ") %>
      </div>
      <div class="col-md-10">
        <%= text_field_tag(:weight) %>
      </div>
      <br/>

      <div class="col-md-2">
      </div>
      <div class="col-md-10">
        <%= submit_tag("Submit") %>
      </div>
      <br/>
    <% end %>
  </div>
<br/>

    <div class="row">
      <div class="col-md-2">
        Activated Output:
      </div>
      <div class="col-md-10">
        &nbsp<%= @output %>
      </div>
    </div>
<br/>

</div>

debete_project_ruby/app/views/perceptrons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_perceptron_path(@perceptron) %> |
<%= link_to 'Back', perceptrons_path %>